#!/bin/bash
prompt="Pick an option:"

doWhat=""
media=""

echo "What do you want to generate ?"
optionsGenerate=("list categories" "generate m3u")
PS3="$prompt "
select opt in "${optionsGenerate[@]}"; do
    case "$REPLY" in
    1)
      doWhat=groups;
      break;;
    2)
      doWhat=m3u;
      break;;
    *) echo "Invalid option.";continue;;
    esac
done

echo "What media ?"
optionsGenerate=("IPTV" "VOD" "SERIES")
PS3="$prompt "
select opt in "${optionsGenerate[@]}"; do
    case "$REPLY" in
    1)
      media=iptv;
      break;;
    2)
      media=vod;
      break;;
    3)
      media=series;
      break;;
    *) echo "Invalid option.";continue;;
    esac
done

echo "Running script..."
npm run $doWhat $media -- "$@"
